[package]
name = "tw_spv"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[features]
default = []
tokio-runtime = ["tokio"]

[dependencies]
byteorder = "1.4"
tokio = { version = "1", features = ["rt-multi-thread", "net", "time", "io-util", "sync"], optional = true }
tw_hash = { path = "../../tw_hash" }
tw_encoding = { path = "../../tw_encoding" }
tw_memory = { path = "../../tw_memory" }
tw_utxo = { path = "../tw_utxo" }

[dev-dependencies]
